# Generated by Django 2.2.7 on 2019-11-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='resume',
            name='address',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resume',
            name='last_name',
            field=models.CharField(default='Bashein', max_length=30),
            preserve_default=False,
        ),
    ]
