# Generated by Django 2.2.7 on 2019-11-21 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(max_length=255)),
                ('severity', models.CharField(max_length=6)),
                ('assignedTo', models.CharField(max_length=60)),
                ('status', models.CharField(max_length=6)),
                ('description', models.TextField()),
            ],
        ),
    ]
