# Generated by Django 2.2.7 on 2019-11-21 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint', models.CharField(max_length=255)),
                ('team', models.CharField(max_length=30)),
                ('version', models.CharField(max_length=5)),
                ('tickets', models.ManyToManyField(to='issue_tracker.Ticket')),
            ],
        ),
    ]
